
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    #network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      ##- /home/certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log/nginx:/var/log/nginx
    depends_on:
      - 3xui


  php:
    image: php:fpm-alpine
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html

  php74:
    image: php:7.4-fpm-alpine
    container_name: php74
    restart: always
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tLcfVedZvVJ2mxHL3YxsFA==
      MYSQL_USER: e5db9173
      MYSQL_PASSWORD: 3HpjKqpAShk=

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data

  3xui:
  ##docker exec 3xui /app/x-ui setting -show
  ##docker exec 3xui /app/x-ui setting -username july -password QaH0um7ym*v4
    image: ghcr.io/mhsanaei/3x-ui
    container_name: 3xui
    restart: always
    #network_mode: host
    ports:
      - "2053:2053"
      - "43344:43344"
    volumes:
      - $PWD/dbxui:/etc/x-ui
      - $PWD/certs:/root/cert
      ##- /home/certs:/root/cert
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    depends_on:
      - php
      - php74
      - redis
      - mysql

