services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    network_mode: host
    #ports:
      #- "80:80"
      #- "443:443"
      #- "443:443/udp"      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - php74
      - mysql
      - redis

  php:
    image: php:fpm-alpine
    container_name: php
    restart: always
    network_mode: host
    volumes:
      - ./html:/var/www/html

  php74:
    image: php:7.4-fpm-alpine
    container_name: php74
    restart: always
    #expose:
      #- "9000"
    ports:
      - "9074:9000"
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    network_mode: host
    #ports:
      #- "3306:3306"
      #- "33060:33060"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: webroot
      MYSQL_USER: kejilion
      MYSQL_PASSWORD: kejilionYYDS

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    network_mode: host
    #ports:
      #- "6379:6379"
    volumes:
      - ./redis:/data
